reima-ecom/reima-theme

demo/content/kids.md, layouts/_default/collection.html
Previously the product sorting dropdown was always shown on the collection pages. Now the dropdown is only shown when all products in the collection are visible. I.e. if there is a limit set (and that limit actually limits the number of products), the dropdown is not shown.
Closes #157
=> fix: Show product sort only when all products shown

layouts/_default/baseof.css, layouts/partials/product.css, layouts/partials/product.html, layouts/partials/product.ts
Now when clicking the review stars (next to the price), there is a scroll to the reviews element / tab (which is opened if closed).
Closes #139
=> fix: Link product page reviews stars to review element

layouts/_default/baseof.css
Currently anchor links don't have any offset when scrolling to it.
Add offset to anchor links via CSS.
Closes #131
=> fix: Add offset to anchor links

layouts/partials/modules/image-links-small.css, layouts/partials/modules/image-links-small.html
Subcategory link items should be aligned to center, not as space between. Subcategory images look pixelated, as if they’ve been upscaled.
Align Subcategory link items to center and and increase image size.
Closes #124
=> fix: Align image links to center and increase image size

importers/lib/files/filesystem.ts, importers/products/domain.d.ts, importers/products/product-generator.ts, importers/products/write-products.ts, importers/shopify/README.md, importers/shopify/cmd.ts, importers/shopify/deps.ts, importers/shopify/products.ts, importers/shopify/products/product-generator.ts, importers/shopify/products/product-image-downloader.ts, importers/shopify/products/product-mapper.ts, importers/shopify/products/sku-parser.test.ts, importers/shopify/products/sku-parser.ts, importers/shopify/products/write-products.test.ts, importers/shopify/products/write-products.ts, layouts/partials/elements/r-carousel.ts, layouts/partials/elements/r-thumbnails.ts, layouts/partials/product.html, layouts/partials/product.ts
This PR adds a new importer script for importing products under `importers/shopify/cmd.ts`. This script currently imports products from Shopify without any images or other media, and downloads product images from the media bank.
Some notes on functionality:
- Product images are downloaded based on the variant SKUs in Shopify
- Existing images are not re-downloaded (matching based on filename only)
- The order of the images is based on the order of variants in Shopify
Downloading images and importing products is completely decoupled now, and product images can just be retrieved with `.Resources.ByType "image"` without any reliance on resource data in the product content frontmatter. The only coupling is that variants now have a `productAndColor` property to be able to find the variant …
=> Add new product importer that downloads images from the media bank

.forestry/front_matter/templates/announcements.yml
Benefits group at Forestry should be visible only if it's enabled.
Add "showOnly" check.
=> fix: Show benefits group only if it’s enabled

.forestry/front_matter/templates/pixels.yml, demo/data/pixels.yaml, layouts/_default/baseof.html, layouts/partials/pixels/gtm-noscript.html, layouts/partials/pixels/gtm.html
Google Tag Manager needs to be added as a pixel option to Forestry.
Add Google Tag Manager setup to partial templates and as an option to Forestry.
Closes: #185
=> feat(gtm-pixel): Add GTM pixel option to Forestry

.forestry/front_matter/templates/product-page-settings.yml
Size guide Pop-up content is not rendered as a table.
Disable Pop-up content wysiwyg editor.
Closes: #207
=> fix(size-guide): Fix size guide content table

layouts/partials/elements/benefits.css, layouts/partials/elements/benefits.html
Benefit bar creates horizontal scrollbar with some browsers, because incorrect top border CSS styling.
Add container element to simplify CSS and fix bug.
Closes #210
=> fix(benefit-bar): Remove horizontal scrolling

layouts/partials/modules/products.css
If there is less than 6 items on product list on desktop breakpoint, items needs to be aligned to center.
Align items to center on desktop breakpoint.
Closes: #216
=> fix(product-list): Center items on product list

.forestry/front_matter/templates/pixels.yml, demo/data/pixels.yaml, layouts/partials/pixels/avantlink.html, layouts/partials/pixels/index.html
Avant Link's affiliate marketing should be enabled for some countries.
Avant Link can be enabled in the same way as other pixels.
=> feat(avant-link): Add Avant Link pixel configuration

demo/products/products/juniors-sweater-vigur/index.html, demo/products/products/juniors-sweater-vigur6/index.html, demo/products/products/juniors-sweater-vigur8/index.html, layouts/partials/modules/products.css, layouts/partials/modules/products.html, layouts/partials/product-price.html
Add discount percentage and "New" tag visually in product listing.
Add discount HTML attribute to provide discount percentage data and add needed CSS.
Closes: #217
=> feat(discounted-product-price): Add discounted product price styling

layouts/partials/modules/products.css
On Mobile breakpoint tags might not fit if discount tag and product tags are visible on same time. This issue will occur if product tag is longer than usually.
Set smaller font sizer on mobile and tablet breakpoints.
Closes: #233
=> fix(product-tags): Fix discount and product tags layout on mobile

.forestry/front_matter/templates/image-grid.yml, demo/content/modules/image-grid.md, layouts/partials/modules/image-grid.css, layouts/partials/modules/image-grid.html
Image Grid needs option to show Image Cards as links. Zoom hover effect needs to be optional.
Add "Image Card as Link" option to Image Grid module and add "Hover effect" option where Zoom effect can be disabled. "Hover effect" option can be used for adding more effect types in future.
Closes: #229
=> feat(image-grid-options): Add links option and set zoom effect as optional

layouts/_default/baseof.ts
When clicking close button on mobile menu, it creates JS error.
Check that element exists before manipulating DOM.
Closes: #256
=> fix(overlay-close): Fix JS error with overlay close

.forestry/front_matter/templates/image-links-small.yml, .forestry/front_matter/templates/image-links.yml
Reima US has some pages that are using old Forestry templates. This is causing error with carousel autoplay speed, if value is not defined.
Change carousel autoplay speed field type to text and set field as optional with 7000 as default value.
=> fix(carousel): Fix carousel autoplay speed nil

layouts/partials/modules/products.css
Product list heading will break layout if it can't fit to viewport.
Remove `width: max-content` CSS rule to allow content flow to multiple rows.
=> fix(products-list): Fix prodcut list heading width

.forestry/front_matter/templates/pixels.yml, demo/data/pixels.yaml, layouts/partials/pixels/index.html, layouts/partials/pixels/mailchimp.html
Mailchimp needs to be added as a pixel option to Forestry.
Add Mailchimp setup to partial templates and as an option to Forestry.
Closes: #266
=> feat(mailchimp-pixel): Add Mailchimp pixel option to Forestry

demo/config.yml, layouts/robots.txt
robots.txt is not enabled on reima-theme.
Enable robots.txt on reima-theme and add layout file for it.
Closes: #262
=> feat(enableRobotsTXT): Enable robots.txt

layouts/robots.txt
Currently only sitemap is need to add to robots.txt
Remove noindex pages list.
=> fix(robots-txt): Remove noindex pages list

layouts/robots.txt
Let's add list of noindex pages to robots.txt.
Loop pages that has noindex enabled and add disallow + URL.
=> feat(robots-txt): Add list of noindex pages

.forestry/front_matter/templates/pixels.yml, demo/data/pixels.yaml, layouts/partials/pixels/ga.html
We need to add Google Ads conversion events to "Add to cart" and "Subscribe to newsletter" events.
Add ID / label options to Forestry and implement scripts to ga.html template.
=> feat(gtag-conversion): Add Google Ads conversion ids

.forestry/front_matter/templates/products.yml
Reima US has some pages that are using TOML formatted templates. This is causing error with carousel autoplay speed, if value is not defined.
Change carousel autoplay speed field type to text and set field as optional with 7000 as default value.
=> fix(products-carousel): Fix carousel autoplay speed nil

layouts/partials/modules/hero.css
In the Hero module, enabling the "Overlay background" setting should create a shadow over the whole image.
Remove background effect from text container and use brightness filter to add designed feature.
Closes: #263
=> fix(hero-overlay-bg): Use brightness filter with bg

demo/products/products/juniors-sweater-vigur7/index.html, i18n/en.json, layouts/partials/elements/r-thumbnails.ts, layouts/partials/product.css, layouts/partials/product.html, layouts/partials/product.modal.css
Add videos to product page
- Videos added to Shopify are displayed as "thumbnails" below the product image - reference https://reima.com/fi/hidden/Lasten-talvihaalari-Stavanger/p/520265-3530
- The video should open in player and start playing when the thumbnail is clicked
- An event is sent to Google Analytics when the video is clicked
Closes: #105
=> feat(product-videos): Add product videos

.forestry/front_matter/templates/menus.yml, demo/data/menus.json, layouts/_default/baseof.html, layouts/partials/menu.css, layouts/partials/modules/image-links-small.html
We need to be able to add image links as additional content to mobile menu.
Add additional content section to Forestry menus and update menu template.
Closes: #284
=> feat(menu): Add additional content section to menu

.forestry/front_matter/templates/translations.yml
Video translation is missing from translations
Add it to Forestry front matter.
=> fix(translations): Add video translation

layouts/partials/product.css, layouts/partials/product.html
Product features would need to be displayed more compact style
Add wrapper elements to product features that it would be possible to so have i.e. 50 / 50 layout.
=> fix(product-features): Add wrapper elements to features

layouts/partials/product.css
Product features would need to be displayed more compact style.
Add CSS class for 50 / 50 layout.
=> feat(product-features): Add 2 column layout

layouts/partials/product.css
Product features would need to be displayed more compact style.
Add flex wrap to fix 50 / 50 layout.
=> fix(product-features): Add flex wrap

layouts/_default/cart.html, layouts/partials/carousel.html, layouts/partials/modules/hero.html, layouts/partials/modules/image-links.html, layouts/partials/modules/milestones.html, layouts/partials/product.html
All `img` tags should have alt attribute.
Add missing `img` alt attributes.
Closes: #300
=> fix(img-alt-attributes): Add missing img alt attributes

.forestry/front_matter/templates/hero.yml, .forestry/front_matter/templates/image-grid.yml, .forestry/front_matter/templates/image-links-small.yml, .forestry/front_matter/templates/image-links.yml, .forestry/front_matter/templates/milestones.yml, .forestry/front_matter/templates/split-card.yml, layouts/partials/img.html, layouts/partials/modules/hero.html, layouts/partials/modules/image-grid.html, layouts/partials/modules/image-links-small.html, layouts/partials/modules/image-links.html, layouts/partials/modules/milestones.html, layouts/partials/modules/split-card.html
This helps from not only an SEO standpoint but also an ADA standpoint in the US (American Disabilities Act) where the alt text reads out what the images look like to the visually impaired.
Added alt text field to front matter templates with an image on forestry.
Added alt attribute to corresponding modules in theme
Added alt attribute to image partials
=> Feat(forestry): Add alt text field/attribute to images on cms/theme

.forestry/front_matter/templates/seo-properties.yml, demo/config.yml, importers/import-collections/content.ts, importers/import-collections/domain.ts, importers/import-collections/queries.ts, layouts/_default/baseof.html
Right now, we currently have a place to put the Meta Description, but not Meta Titles. These need to be different than the H1 on the page. Right now, it's supposed to pull in from Shopify but oftentimes does not.
-added correct field to forestry front matter template  seo properties
-title now is conditionally rendered in following order: 
1. use seotitle field
2. if seotitle is empty, use title of page/collection/product. this is printed like so: "Coffee Bean Shimmer | Reima USA"
=> feat(meta-title-forestry): add meta title to forestry

layouts/partials/carousel.html, layouts/partials/elements/benefits.html, layouts/partials/helpers/humanize-image-filename.html, layouts/partials/image.html, layouts/partials/img.html, layouts/partials/modules/hero.html, layouts/partials/modules/image-links.html, layouts/partials/modules/milestones.html, layouts/partials/modules/testimonials.html, layouts/partials/product.html
#Why
Use image name as alt text, if alt is empty in Forestry/Shopify 
#How
Created a new partial that [humanizes](https://gohugo.io/functions/humanize/) image filenames and img alt text defaults to this if no defined alt present from Forestry and Shopify.
=> Feat(alt text): defaults to image name

layouts/_default/baseof.html
#why
link preview will have an image of the product, for ux
#how
fetches the 1st product image and if not found, defaults to R logo
closes #327
=> feat(og-image): 1st product image used as og:image

layouts/partials/product.ts
Strikethrough price is displayed on PDP for all color variants if the first variant is discounted
Looped over all elements as there are 2 different price elements, for mobile and desktop. Earlier code only selected the first element (mobile)
closes #329
=> fix(pdp-price): strikethrough price shows only if it exists

.forestry/front_matter/templates/hero.yml, layouts/partials/helpers/get-video-padding.html, layouts/partials/modules/hero.css, layouts/partials/modules/hero.html
#Why
Current setup in hero only accommodates certain aspect ratio videos for Vimeo and no option for specific mobile video. iframe needs to have a fixed padding according to the video aspect ratio.
#How
- Created Forestry fields for aspect ratio and vimeo id mobile.
- Added functionality to hero module, that conditionally renders videos according to created fields and generates a padding top from from the aspect ratio
=> feat(hero-vimeo-mobile): mobile version of vimeo video

layouts/_default/search.css
search filter close button was displayed when filter selections was focused on desktop
display: none; on close button desktop width
=> fix(search-filter): hide close button on desktop

layouts/partials/product.html
PDP thumbnail image alts were coming from the main image alt variable
defined alt variable inside thumbnail range
=> fix(product-page): thumbnail alts bug fix

layouts/_default/collection.css
product list carousel was overflowing viewport on mobile
css styling of grid template columns
=> fix(carousel): fixed issue with mobile overflow

layouts/_default/collection.css
desktop overflow problem due to earlier carousel stylings
styled grid template columns minmax(500px, 1fr)
=> fix(collection): minmax grid template columns

layouts/partials/modules/products.css, layouts/partials/modules/products.html
"Show all" button is not visible with mobile product carousel immediately
Conditional rendering in template of the "show all" button
=> Fix(product carousel): product carousel mobile more button moved to under carousel 

layouts/_default/status.html
Netlify builds have been unreliable lately. This ensures that the content manager has at least some information on the netlify status if there is a problem with the build
Added Netlify status badge to /status for content managers to see the page build status
=> feat(netlify-status): added badge to status.html

.forestry/front_matter/templates/collection.yml
We use multiple lists per page, i.e. to add content blocks between lists. In those cases it makes the multiple floating filters appear at the same time and the results are unnecessary.
Add a toggle on forestry and conditional that hides the filter
=> feat(collection-filter):  option to hide product filter from collection page

demo/products/collections/tops/products/juniors-sweater-vigur.md, demo/products/collections/tops/products/juniors-sweater-vigur6.md, demo/products/collections/tops/products/juniors-sweater-vigur7.md, demo/products/collections/tops/products/juniors-sweater-vigur8.md, demo/products/collections/tops/products/juniors-sweater-winged.md, demo/products/collections/tops/products/kids-sweater-mahin.md, importers/import-collections/content.ts, layouts/partials/modules/products.html
Currently collection page products have unique URL and that multiplies rendering time.
Collection products pages won't be rendered any more and we will use just one URL for single product page.
=> fix(collection-products): Remove custom URL from collection products

layouts/partials/helpers/get-link.html
get-link is calling link partial without checking .RelPermalink value and it could cause error.
Check .RelPermalink value before calling link partial.
=> fix(get-link): Check .RelPermalink before calling partial

layouts/partials/modules/split-card.html
split-card module is calling img partial without checking .image value and it could cause error.
Check .image value before calling link partial.
=> fix(split-card): Check .image before calling partial
