- layouts/_default/baseof.html
- layouts/_default/collection.html
- layouts/_default/page.html
- layouts/partials/modules/products.css
- layouts/partials/modules/products.html
- layouts/partials/modules/products.ts
> Change product list image when clicking color swatch

- .forestry/front_matter/templates/menus.yml
- .forestry/front_matter/templates/pixels.yml
- .forestry/front_matter/templates/product-page-settings.yml
- demo/data/productpage.yaml
- layouts/partials/product.css
- layouts/partials/product.html
> Payment logos

- .forestry/front_matter/templates/menus.yml
- .forestry/front_matter/templates/pixels.yml
- demo/data/pixels.yaml
- layouts/_default/baseof.html
- layouts/partials/pixels/criteo.html
- layouts/partials/pixels/index.html
- layouts/partials/pixels/pinterest.html
- layouts/partials/pixels/taboola.html
Closes #77 
See issue for more info
> Add Pinterest, Taboola, and Criteo pixels

- demo/data/announcements.fi.json
- demo/data/menus.json
- importers/products/write-products-legacy.ts
- layouts/_default/baseof.css
- layouts/partials/breadcrumb.css
- layouts/partials/product-reviews.css
- layouts/partials/product.css
- layouts/partials/product.html
Product page design should be as close to the design mockup as possible.
Closes #48
> Improve product page design

- .forestry/front_matter/templates/pixels.yml
- .forestry/front_matter/templates/translations.yml
- demo/data/pixels.yaml
- layouts/partials/pixels/ga.html
Now utilizing gtag (universal analytics)
> Add Google Ads tracking

- content/frosmo.md
- layouts/_default/frosmo.json
> Add frosmo.json feed

- .forestry/front_matter/templates/pixels.yml
- demo/data/pixels.yaml
- layouts/partials/pixels/index.html
- layouts/partials/pixels/luckyorange.html
Lucky Orange should be enabled for some countries.
Lucky Orange can be enabled in the same way as other pixels.  
Closes #147
> feat: Add Lucky Orange pixel configuration

- layouts/_default/collection.css
- layouts/_default/collection.html
- layouts/_default/collection.ts
- layouts/partials/modules/products.html
Filter on mobile should be under hero/content + add filter and sorting on the same row.
Refactor sidebar position by modifying HTML & CSS.
Closes #140
> fix: Fix filters position on collection page

- .forestry/front_matter/templates/pixels.yml
- demo/data/pixels.yaml
- layouts/partials/pixels/googleoptimize.html
- layouts/partials/pixels/index.html
Google Optimize needs to be added as a pixel option to Forestry.
Add Google Optimize setup to partial templates and as an option to Forestry.
Closes: #197
> feat(googleoptimize-pixel): Add Google Optimize pixel option to Forestry

- .forestry/front_matter/templates/pixels.yml
Google Optimize Forestry frontmatter config is broken
Fix config formation
Closes: #201
> fix: pixels.yml format

- .forestry/front_matter/templates/announcements.yml
- .forestry/front_matter/templates/menus.yml
- .forestry/front_matter/templates/pixels.yml
- demo/data/menus.json
- layouts/_default/baseof.header-critical.css
- layouts/_default/baseof.html
Adds ability to create "extra menu items" for the main menu. These are shown at the top level of the main menu, but not quite as prominently as the other menu items.
Closes #225
> Add extra menu item configuration

- .forestry/front_matter/templates/form.yml
- .forestry/front_matter/templates/page.yml
- demo/content/modules/form.md
- demo/data/menus.json
- layouts/_default/baseof.html
- layouts/partials/elements/r-newsletter.ts
- layouts/partials/modules/form.css
- layouts/partials/modules/form.html
- layouts/partials/modules/form.ts
Form module is needed for creating Babybox signup form.
Add form module to Forestry and add new option to page template so that newsletter form can be hidden.
Closes: #250
> feat(form-module): Add form module

- demo/content/modules/form.md
- layouts/partials/modules/form.html
Tags data is not added to form input.
Add tags data to form input properly.
> fix(form-module): Fix tags input

- .gitignore
- layouts/_default/search.css
- layouts/_default/search.html
- layouts/_default/search.ts
- layouts/partials/elements/r-search-filters.css
- layouts/partials/elements/r-search-filters.html
- layouts/partials/elements/r-search-filters.ts
- layouts/partials/elements/r-search-loop.css
- layouts/partials/elements/r-search-results.css
- layouts/partials/elements/r-search-results.html
- layouts/partials/elements/r-search-results.ts
- layouts/partials/elements/search-domain.ts
- layouts/partials/elements/search-loop54.ts
> Add filtering to search results page

- .forestry/front_matter/templates/product-page-settings.yml
- demo/data/productpage.yaml
- layouts/partials/product-payments-benefits-links.html
- layouts/partials/product.css
- layouts/partials/product.html
Update payments & benefits information based on reimadesign.com.
Update HTML structure to support design and add new content section to Forestry.
Closes: #292
> feat(payment-benefits): Add payments benefits block

- layouts/_default/baseof.html
- layouts/_default/search.ts
- layouts/partials/elements/r-search-autocomplete.css
- layouts/partials/elements/r-search-autocomplete.html
- layouts/partials/elements/r-search-autocomplete.ts
- layouts/partials/elements/r-search-categories.css
- layouts/partials/elements/r-search-categories.html
- layouts/partials/elements/r-search-categories.ts
- layouts/partials/elements/r-search-loop.html
- layouts/partials/elements/r-search-loop.ts
- layouts/partials/elements/r-search-results.html
- layouts/partials/elements/r-search-results.ts
- layouts/partials/elements/search-domain.ts
- layouts/partials/elements/search-loop54.ts
> Add auto complete and category search to search widget

- demo/products/products/juniors-sweater-vigur7/index.html
- layouts/partials/product.html
Product page videos don't work at the moment.
Fix product video URL naming.
> fix(product-video): Fix product video URL

- importers/products/domain.d.ts
- importers/products/product-generator.ts
- importers/products/write-products.ts
- importers/shopify/products/product-generator.ts
Product videos are not imported on imports-products script.
Add product video URLs to product page data.
> feat(import-product-videos): Import video data

- layouts/_default/baseof.ts
Modal video is not stopped when modal is closed.
Bind video play and pause functionalities to open and close events.
> fix(modal-video): Fix modal video open and close

- layouts/partials/product.css
Fix payment logos layout.
Remove margin from last child.
> fix(payment-logos): Fix last child margin

- layouts/_default/baseof.css
- layouts/partials/product.css
- layouts/partials/product.html
PDP title / header should be updated to follow reimadesign.com.
Update PDP header and title typography.
Closes: #294
> feat(pdp-title): Update PDP title

- layouts/_default/baseof.css
- layouts/partials/product.ts
Sale price don't update correctly on new PDP header.
Update sale price correctly on all price elements.
> fix(pdp-header): Fix pdp header sale price

- .forestry/front_matter/templates/collection.yml
- demo/content/collection.html
- demo/products/collections/tops/_index.md
Collection page template don't support testimonials module.
Add testimonials module support to collections page template.
Closes: #310
> feat(collection-page): Add testimonials template

- layouts/partials/carousel.html
- layouts/partials/image.html
- layouts/partials/modules/hero.html
- layouts/partials/modules/image-links.html
- layouts/partials/modules/milestones.html
- layouts/partials/product.html
there was an error with null valued data going into humanizer helper
Define default value for $alt
> fix(alt-text): default $alt value

- layouts/_default/baseof.header-critical.css
- layouts/_default/baseof.html
- layouts/_default/collection.css
- layouts/_default/collection.html
- layouts/_default/search.css
- layouts/_default/search.html
- layouts/_default/search.ts
- layouts/partials/elements/r-carousel.css
- layouts/partials/elements/r-cart.css
- layouts/partials/elements/r-cart.html
- layouts/partials/elements/r-cart.ts
- layouts/partials/elements/r-search-filters.css
- layouts/partials/elements/r-search-loop.css
- layouts/partials/modules/products.html
- layouts/partials/product.css
- layouts/partials/product.html
Parts of site are not ada compliant
closes 
#340 
Closes #344
> fix(accessibility): ada accessibility issues

- layouts/partials/carousel.css
- layouts/partials/modules/products.css
fix product list carousel elements cutting out or peeking in
css styling
> fix(product-list-carousel): fixes

- importers/products/domain.d.ts
- importers/products/product-generator.ts
- importers/products/write-products.ts
- layouts/partials/image.html
- layouts/partials/product.html
Shopify image alt texts have not been pulled by shopify
added alt text to query and product generator on importer, product and image partials on frontend
Closes:  #300
> Feat(product alt text): product alt text is imported from shopify

- layouts/partials/carousel.css
- layouts/partials/modules/products.css
gap adds space in carousel
Negative margin-right to mitigate gap
> fix(product-carousel): margin right correction

- layouts/partials/elements/r-search-results.html
- layouts/partials/elements/r-search-results.ts
- layouts/partials/elements/search-loop54.ts
discount prices not showing on search results
added typescript field campaignPrice and a span to template, campaign price is visible if campaignPrice is not equal to price
> feat(search-price): search discount strikethrough

- demo/products/products/juniors-sweater-vigur/index.html
- layouts/partials/product.html
If first size is unavailable, the color swatch is likewise styled unavailable
If any size of that color is available, swatch is initially styled available
> Fix(PDP color swatch): initial color availability

- importers/reviews-yotpo/workflow.ts
Reviews were displayed by oldest order first
sorted reviews in the importer by newest date
> feat(reviews-order): newest first

- .forestry/front_matter/templates/collection.yml
- .forestry/front_matter/templates/page.yml
- .forestry/front_matter/templates/schema-org-structured-data.yml
- layouts/_default/collection.html
- layouts/_default/page.html
- layouts/partials/product.html
Pages from forestry should have a schema.org structured data for SEO purposes
added schema frontmatter to forestry and render on page & collection
> Feat(schema markup): add schema markup to page & collection

- .forestry/front_matter/templates/collection.yml
- layouts/_default/collection.html
option to hide product list count on collection page in forestry
added productCount toggle field on collections frontmatter and on frontend collection page now renders conditionally
> Feat(hide collection product count): add toggle in forestry & frontend cond. render

- demo/products/collections/tops/products/juniors-sweater-vigur.md
- demo/products/collections/tops/products/juniors-sweater-vigur6.md
- demo/products/collections/tops/products/juniors-sweater-vigur7.md
- demo/products/collections/tops/products/juniors-sweater-vigur8.md
- demo/products/collections/tops/products/juniors-sweater-winged.md
- demo/products/collections/tops/products/kids-sweater-mahin.md
- importers/import-collections/content.ts
Fix collection page render method.
Modify collection page render method.
> fix(collection-products): Fix collection page render method

- demo/data/reviews.json
- importers/reviews-yotpo/cmd.ts
- importers/reviews-yotpo/get-media.ts
- importers/reviews-yotpo/get-reviews.ts
- importers/reviews-yotpo/get-utoken.ts
- importers/reviews-yotpo/workflow.ts
- layouts/_default/baseof.header-critical.css
- layouts/partials/product-reviews.css
- layouts/partials/product-reviews.html
- layouts/partials/product.css
- layouts/partials/product.modal.css
Yotpo Reviews have images
The regular get reviews endpoint doesn't pull media, so I had to:
Create a data pull from the Yotpo get-media API endpoint and merged the media data with reviews that correspond to the id. 
Created a thumbnail section on the frontend in a review, with a modal opening on click
> Feat(yotpo review images)

- layouts/partials/consent-banners.css
#382 
Change consent-banner background color to #f2f2f5 
closes:
#382
> style(consent-banner): bg color to light grey

- demo/data/pixels.yaml
- layouts/_default/baseof.html
- layouts/partials/pixels/adform/collection-script.html
- layouts/partials/pixels/adform/content-page-script.html
- layouts/partials/pixels/adform/homepage-script.html
- layouts/partials/pixels/adform/product-page-script.html
- layouts/partials/product.html
add adform scripts to frontend
conditional rendering of different adform scripts in baseof.html & product.html according to page layout and forestry
> feat(adform-scripts): add scripts to frontend

- layouts/partials/carousel.html
- layouts/partials/image.html
- layouts/partials/modules/hero.html
- layouts/partials/modules/image-links.html
- layouts/partials/product.html
remove fixed height/width from images after Hugo image properties are no longer available
> fix(images): remove fixed height/width

- layouts/partials/elements/r-search-categories.ts
What is the problem that this PR is intended to solve?
In what way does the code included in this PR solve the problem above?
> fix(search-bug): remove slash from query
